name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like
      placeholder: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: This would help when...
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How you'd like it to work
      placeholder: It could work by...
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other solutions or features you've considered
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
